name: base
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.8,<4
    - pip
    - numpy-base>=1.18
    - numpy>=1.18
    - scipy>=1.4.0
    - pandas>=0.25
    - dask>=2.6.0
    - imagecodecs>=2020.5.30
    - pip:
        - tifffile==2021.2.1
        - PyYAML>=5.3.0
        - aicsimageio==3.3.4
        - czifile==2019.7.2
        - lxml~=4.5.1
        - matplotlib>=3.2.1
        - scikit-image>=0.17.2
        - scikit-learn>=0.23.1
        - shapely~=1.7.0
        - opencv-contrib-python-headless>=4.0,<5
        - psutil~=5.9.0
